### ISSUE TITLE
Failed to import package torch_geometric_autoscale

### ISSUE THREAD

**Issue by EnjianGong** [rusty1s/pyg_autoscale#22]
my env is 
torch                         1.12.0
torch-cluster                 1.6.0
torch-geometric               2.0.4
torch-geometric-autoscale     0.0.0
torch-scatter                 2.0.9
torch-sparse                  0.6.15
torch-spline-conv             1.2.1

The import command is blocked until ctrl+c, then throw exception 

from torch_geometric_autoscale import History, AsyncIOPool
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/torch_geometric_autoscale/__init__.py", line 12, in <module>
    from .data import get_data  # noqa
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/torch_geometric_autoscale/data.py", line 9, in <module>
    from ogb.nodeproppred import PygNodePropPredDataset
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/ogb/nodeproppred/__init__.py", line 1, in <module>
    from .evaluate import Evaluator
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/ogb/nodeproppred/evaluate.py", line 1, in <module>
    from sklearn.metrics import roc_auc_score
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/sklearn/utils/__init__.py", line 26, in <module>
    from . import _joblib
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/sklearn/utils/_joblib.py", line 7, in <module>
    import joblib
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/joblib/__init__.py", line 113, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/joblib/memory.py", line 32, in <module>
    from ._store_backends import StoreBackendBase, FileSystemStoreBackend
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/joblib/_store_backends.py", line 15, in <module>
    from .backports import concurrency_safe_rename
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/joblib/backports.py", line 7, in <module>
    from distutils.version import LooseVersion
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 97, in find_spec
    return method()
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/_distutils_hack/__init__.py", line 108, in spec_for_distutils
    mod = importlib.import_module('setuptools._distutils')
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/home/ma-user/anaconda3/envs/py3.9/lib/python3.9/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 211, in _lock_unlock_module
  File "<frozen importlib._bootstrap>", line 107, in acquire
KeyboardInterrupt

**Comment by rusty1s** [comment]
Looks to be an issue with your `sklearn` installation. Is it possible to run
```
import sklearn
```
or
```
import ogb
```
on your end?
