### ISSUE TITLE
Attribute Error while importing torch_geometric_autoscale

### ISSUE THREAD

**Issue by marmg** [rusty1s/pyg_autoscale#28]
When I try to run the benchmark examples, I get this error:

```
Traceback (most recent call last):
  File "repos/pyg_autoscale/small_benchmark/main.py", line 8, in <module>
    from torch_geometric_autoscale import (get_data, metis, permute, models,
  File "repos/pyg_autoscale/torch_geometric_autoscale/__init__.py", line 10, in <module>
    library, [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'
```

I have these versions:
- `python` 3.9.16
- `torch` 2.1.0
- `torch_geometric` 2.4.0
- `torch-geometric-autoscale` 0.0.0
- `torch-scatter` 2.0.9
- `torch-sparse` 0.6.18

No cuda. MacBook Pro macOS 14.0.

Edit: According to https://github.com/pyg-team/pytorch_geometric/issues/2304 I have checked in my env folder and I can see the `*.so` files:
- `_async.so`
- `_relabel.so`

**Comment by rusty1s** [comment]
This looks to be an installation issue, so might be good to share what `python setup.py install` returns for you. On a different note: This package is not tested for macOS :(

**Comment by marmg** [comment]
This is the output:

```
running bdist_egg
running egg_info
writing manifest file 'torch_geometric_autoscale.egg-info/SOURCES.txt'
running install_lib
running build_py
creating build/lib.macosx-12-x86_64-3.9
creating build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale
copying torch_geometric_autoscale/__init__.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale
copying torch_geometric_autoscale/utils.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale
copying torch_geometric_autoscale/loader.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale
copying torch_geometric_autoscale/pool.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale
copying torch_geometric_autoscale/data.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale
copying torch_geometric_autoscale/metis.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale
copying torch_geometric_autoscale/history.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale
creating build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale/models
copying torch_geometric_autoscale/models/gcn.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale/models
copying torch_geometric_autoscale/models/appnp.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale/models
copying torch_geometric_autoscale/models/pna.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale/models
copying torch_geometric_autoscale/models/__init__.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale/models
copying torch_geometric_autoscale/models/gcn2.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale/models
copying torch_geometric_autoscale/models/pna_jk.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale/models
copying torch_geometric_autoscale/models/gat.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale/models
copying torch_geometric_autoscale/models/base.py -> build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale/models
running build_ext
creating build/temp.macosx-12-x86_64-3.9
creating build/temp.macosx-12-x86_64-3.9/csrc
creating build/temp.macosx-12-x86_64-3.9/csrc/cpu
/usr/local/opt/llvm/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Icsrc -I/venv/lib/python3.9/site-packages/torch/include -I/venv/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/venv/lib/python3.9/site-packages/torch/include/TH -I/venv/lib/python3.9/site-packages/torch/include/THC -I/venv/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c csrc/cpu/relabel_cpu.cpp -o build/temp.macosx-12-x86_64-3.9/csrc/cpu/relabel_cpu.o -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_clang\" -DPYBIND11_STDLIB=\"_libcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1002\" -DTORCH_EXTENSION_NAME=_relabel -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
/usr/local/opt/llvm/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Icsrc -I/venv/lib/python3.9/site-packages/torch/include -I/venv/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/venv/lib/python3.9/site-packages/torch/include/TH -I/venv/lib/python3.9/site-packages/torch/include/THC -I/venv/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c csrc/relabel.cpp -o build/temp.macosx-12-x86_64-3.9/csrc/relabel.o -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_clang\" -DPYBIND11_STDLIB=\"_libcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1002\" -DTORCH_EXTENSION_NAME=_relabel -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
clang++ -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk build/temp.macosx-12-x86_64-3.9/csrc/cpu/relabel_cpu.o build/temp.macosx-12-x86_64-3.9/csrc/relabel.o -L/venv/lib/python3.9/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale/_relabel.so
ld: warning: ignoring duplicate libraries: '-lc10', '-ltorch', '-ltorch_cpu', '-ltorch_python'
/usr/local/opt/llvm/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Icsrc -I/venv/lib/python3.9/site-packages/torch/include -I/venv/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/venv/lib/python3.9/site-packages/torch/include/TH -I/venv/lib/python3.9/site-packages/torch/include/THC -I/venv/include -I/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c csrc/async.cpp -o build/temp.macosx-12-x86_64-3.9/csrc/async.o -DAT_PARALLEL_OPENMP -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_clang\" -DPYBIND11_STDLIB=\"_libcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1002\" -DTORCH_EXTENSION_NAME=_async -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
clang++ -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk build/temp.macosx-12-x86_64-3.9/csrc/async.o -L/venv/lib/python3.9/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.macosx-12-x86_64-3.9/torch_geometric_autoscale/_async.so
ld: warning: ignoring duplicate libraries: '-lc10', '-ltorch', '-ltorch_cpu', '-ltorch_python'
creating build/bdist.macosx-12-x86_64
creating build/bdist.macosx-12-x86_64/egg
creating build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale
creating build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/models
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/models/gcn.py to gcn.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/models/appnp.py to appnp.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/models/pna.py to pna.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/models/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/models/gcn2.py to gcn2.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/models/pna_jk.py to pna_jk.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/models/gat.py to gat.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/models/base.py to base.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/utils.py to utils.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/loader.py to loader.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/pool.py to pool.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/data.py to data.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/metis.py to metis.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/history.py to history.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/_relabel.py to _relabel.cpython-39.pyc
byte-compiling build/bdist.macosx-12-x86_64/egg/torch_geometric_autoscale/_async.py to _async.cpython-39.pyc
creating build/bdist.macosx-12-x86_64/egg/EGG-INFO
copying torch_geometric_autoscale.egg-info/PKG-INFO -> build/bdist.macosx-12-x86_64/egg/EGG-INFO
copying torch_geometric_autoscale.egg-info/SOURCES.txt -> build/bdist.macosx-12-x86_64/egg/EGG-INFO
copying torch_geometric_autoscale.egg-info/dependency_links.txt -> build/bdist.macosx-12-x86_64/egg/EGG-INFO
copying torch_geometric_autoscale.egg-info/requires.txt -> build/bdist.macosx-12-x86_64/egg/EGG-INFO
copying torch_geometric_autoscale.egg-info/top_level.txt -> build/bdist.macosx-12-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
torch_geometric_autoscale.__pycache__.__init__.cpython-39: module references __file__
torch_geometric_autoscale.__pycache__._async.cpython-39: module references __file__
torch_geometric_autoscale.__pycache__._relabel.cpython-39: module references __file__
removing 'build/bdist.macosx-12-x86_64/egg' (and everything under it)
creating /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg
Extracting torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg to /venv/lib/python3.9/site-packages
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/__init__.py to __init__.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/_async.py to _async.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/_relabel.py to _relabel.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/data.py to data.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/history.py to history.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/loader.py to loader.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/metis.py to metis.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/pool.py to pool.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/utils.py to utils.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/models/__init__.py to __init__.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/models/appnp.py to appnp.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/models/base.py to base.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/models/gat.py to gat.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/models/gcn.py to gcn.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/models/gcn2.py to gcn2.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/models/pna.py to pna.cpython-39.pyc
byte-compiling /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg/torch_geometric_autoscale/models/pna_jk.py to pna_jk.cpython-39.pyc
Adding torch-geometric-autoscale 0.0.0 to easy-install.pth file

Installed /venv/lib/python3.9/site-packages/torch_geometric_autoscale-0.0.0-py3.9-macosx-12-x86_64.egg

Processing dependencies for torch-geometric-autoscale==0.0.0
Searching for hydra-core
Reading https://pypi.org/simple/hydra-core/
Downloading https://files.pythonhosted.org/packages/c6/50/e0edd38dcd63fb26a8547f13d28f7a008bc4a3fd4eb4ff030673f22ad41a/hydra_core-1.3.2-py3-none-any.whl#sha256=fa0238a9e31df3373b35b0bfb672c34cc92718d21f81311d8996a16de1141d8b
Best match: hydra-core 1.3.2
Processing hydra_core-1.3.2-py3-none-any.whl
Installing hydra_core-1.3.2-py3-none-any.whl to /venv/lib/python3.9/site-packages
Adding hydra-core 1.3.2 to easy-install.pth file

Installed /venv/lib/python3.9/site-packages/hydra_core-1.3.2-py3.9.egg
Searching for ogb
Reading https://pypi.org/simple/ogb/
Downloading https://files.pythonhosted.org/packages/7e/95/e0770cf1ad9667492f56b732f44398ef2756d61df914e10d121a3cad013a/ogb-1.3.6-py3-none-any.whl#sha256=29ab84078c66a7846bf137c9be9545978616a053e734c032a2ff731d026bb5e9
Best match: ogb 1.3.6
Processing ogb-1.3.6-py3-none-any.whl
Installing ogb-1.3.6-py3-none-any.whl to /venv/lib/python3.9/site-packages
Adding ogb 1.3.6 to easy-install.pth file

Installed /venv/lib/python3.9/site-packages/ogb-1.3.6-py3.9.egg
Searching for packaging
Reading https://pypi.org/simple/packaging/
Downloading https://files.pythonhosted.org/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl#sha256=8c491190033a9af7e1d931d0b5dacc2ef47509b34dd0de67ed209b5203fc88c7
Best match: packaging 23.2
Processing packaging-23.2-py3-none-any.whl
Installing packaging-23.2-py3-none-any.whl to /venv/lib/python3.9/site-packages
Adding packaging 23.2 to easy-install.pth file

Installed /venv/lib/python3.9/site-packages/packaging-23.2-py3.9.egg
Searching for omegaconf<2.4,>=2.2
Reading https://pypi.org/simple/omegaconf/
Downloading https://files.pythonhosted.org/packages/e3/94/1843518e420fa3ed6919835845df698c7e27e183cb997394e4a670973a65/omegaconf-2.3.0-py3-none-any.whl#sha256=7b4df175cdb08ba400f45cae3bdcae7ba8365db4d165fc65fd04b050ab63b46b
Best match: omegaconf 2.3.0
Processing omegaconf-2.3.0-py3-none-any.whl
Installing omegaconf-2.3.0-py3-none-any.whl to /venv/lib/python3.9/site-packages
Adding omegaconf 2.3.0 to easy-install.pth file

Installed /venv/lib/python3.9/site-packages/omegaconf-2.3.0-py3.9.egg
Searching for antlr4-python3-runtime==4.9.*
Reading https://pypi.org/simple/antlr4-python3-runtime/
Downloading https://files.pythonhosted.org/packages/3e/38/7859ff46355f76f8d19459005ca000b6e7012f2f1ca597746cbcd1fbfe5e/antlr4-python3-runtime-4.9.3.tar.gz#sha256=f224469b4168294902bb1efa80a8bf7855f24c99aef99cbefc1bcd3cce77881b
Best match: antlr4-python3-runtime 4.9.3
Processing antlr4-python3-runtime-4.9.3.tar.gz
Writing /var/folders/0w/lmm8ryyx5wq8qdwfny4vh48h0000gn/T/easy_install-ekomto8v/antlr4-python3-runtime-4.9.3/setup.cfg
Running antlr4-python3-runtime-4.9.3/setup.py -q bdist_egg --dist-dir /var/folders/0w/lmm8ryyx5wq8qdwfny4vh48h0000gn/T/easy_install-ekomto8v/antlr4-python3-runtime-4.9.3/egg-dist-tmp-8v2v09rm
warning: no files found matching '*.py' under directory 'test'
warning: no files found matching '*.c' under directory 'test'
/venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
zip_safe flag not set; analyzing archive contents...
Copying antlr4_python3_runtime-4.9.3-py3.9.egg to /venv/lib/python3.9/site-packages
Adding antlr4-python3-runtime 4.9.3 to easy-install.pth file
Installing pygrun script to /venv/bin

Installed /venv/lib/python3.9/site-packages/antlr4_python3_runtime-4.9.3-py3.9.egg
Searching for six>=1.12.0
Reading https://pypi.org/simple/six/
/venv/lib/python3.9/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Downloading https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl#sha256=8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254
Best match: six 1.16.0
Processing six-1.16.0-py2.py3-none-any.whl
Installing six-1.16.0-py2.py3-none-any.whl to /venv/lib/python3.9/site-packages
Adding six 1.16.0 to easy-install.pth file

Installed /venv/lib/python3.9/site-packages/six-1.16.0-py3.9.egg
Searching for pandas>=0.24.0
Reading https://pypi.org/simple/pandas/
Downloading https://files.pythonhosted.org/packages/f9/57/5fbdd9f42204691adac1280a9731abba77df604c7998b6c10433219abcad/pandas-2.1.1-cp39-cp39-macosx_10_9_x86_64.whl#sha256=366da7b0e540d1b908886d4feb3d951f2f1e572e655c1160f5fde28ad4abb750
Best match: pandas 2.1.1
Processing pandas-2.1.1-cp39-cp39-macosx_10_9_x86_64.whl
Installing pandas-2.1.1-cp39-cp39-macosx_10_9_x86_64.whl to /venv/lib/python3.9/site-packages
Adding pandas 2.1.1 to easy-install.pth file

Installed /venv/lib/python3.9/site-packages/pandas-2.1.1-py3.9-macosx-12-x86_64.egg
Searching for outdated>=0.2.0
Reading https://pypi.org/simple/outdated/
Downloading https://files.pythonhosted.org/packages/d3/04/7d2b9a0d1b81e30f39e6f358bac01f4f18b585f35b0ffc5c83fc274f146b/outdated-0.2.2-py2.py3-none-any.whl#sha256=3e9c2ee6d17e86ae8cc7bb71d70c4172690121cda367155a30994742172678c8
Best match: outdated 0.2.2
Processing outdated-0.2.2-py2.py3-none-any.whl
Installing outdated-0.2.2-py2.py3-none-any.whl to /venv/lib/python3.9/site-packages
Adding outdated 0.2.2 to easy-install.pth file

Installed /venv/lib/python3.9/site-packages/outdated-0.2.2-py3.9.egg
Searching for PyYAML>=5.1.0
Reading https://pypi.org/simple/PyYAML/
Downloading https://files.pythonhosted.org/packages/57/c5/5d09b66b41d549914802f482a2118d925d876dc2a35b2d127694c1345c34/PyYAML-6.0.1-cp39-cp39-macosx_10_9_x86_64.whl#sha256=9eb6caa9a297fc2c2fb8862bc5370d0303ddba53ba97e71f08023b6cd73d16a8
Best match: PyYAML 6.0.1
Processing PyYAML-6.0.1-cp39-cp39-macosx_10_9_x86_64.whl
Installing PyYAML-6.0.1-cp39-cp39-macosx_10_9_x86_64.whl to /venv/lib/python3.9/site-packages
Adding PyYAML 6.0.1 to easy-install.pth file

Installed /venv/lib/python3.9/site-packages/PyYAML-6.0.1-py3.9-macosx-12-x86_64.egg
Searching for tzdata>=2022.1
Reading https://pypi.org/simple/tzdata/
Downloading https://files.pythonhosted.org/packages/d5/fb/a79efcab32b8a1f1ddca7f35109a50e4a80d42ac1c9187ab46522b2407d7/tzdata-2023.3-py2.py3-none-any.whl#sha256=7e65763eef3120314099b6939b5546db7adce1e7d6f2e179e3df563c70511eda
Best match: tzdata 2023.3
Processing tzdata-2023.3-py2.py3-none-any.whl
Installing tzdata-2023.3-py2.py3-none-any.whl to /venv/lib/python3.9/site-packages
Adding tzdata 2023.3 to easy-install.pth file

Installed /venv/lib/python3.9/site-packages/tzdata-2023.3-py3.9.egg
Searching for pytz>=2020.1
Reading https://pypi.org/simple/pytz/
Downloading https://files.pythonhosted.org/packages/32/4d/aaf7eff5deb402fd9a24a1449a8119f00d74ae9c2efa79f8ef9994261fc2/pytz-2023.3.post1-py2.py3-none-any.whl#sha256=ce42d816b81b68506614c11e8937d3aa9e41007ceb50bfdcb0749b921bf646c7
Best match: pytz 2023.3.post1
Processing pytz-2023.3.post1-py2.py3-none-any.whl
Installing pytz-2023.3.post1-py2.py3-none-any.whl to /venv/lib/python3.9/site-packages
Adding pytz 2023.3.post1 to easy-install.pth file

Installed /venv/lib/python3.9/site-packages/pytz-2023.3.post1-py3.9.egg
Searching for python-dateutil>=2.8.2
Reading https://pypi.org/simple/python-dateutil/
Downloading https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl#sha256=961d03dc3453ebbc59dbdea9e4e11c5651520a876d0f4db161e8674aae935da9
Best match: python-dateutil 2.8.2
Processing python_dateutil-2.8.2-py2.py3-none-any.whl
Installing python_dateutil-2.8.2-py2.py3-none-any.whl to /venv/lib/python3.9/site-packages
Adding python-dateutil 2.8.2 to easy-install.pth file

Installed /venv/lib/python3.9/site-packages/python_dateutil-2.8.2-py3.9.egg
Searching for littleutils
Reading https://pypi.org/simple/littleutils/
Downloading https://files.pythonhosted.org/packages/4e/b1/bb4e06f010947d67349f863b6a2ad71577f85590180a935f60543f622652/littleutils-0.2.2.tar.gz#sha256=e6cae3a4203e530d51c9667ed310ffe3b1948f2876e3d69605b3de4b7d96916f
Best match: littleutils 0.2.2
Processing littleutils-0.2.2.tar.gz
Writing /var/folders/0w/lmm8ryyx5wq8qdwfny4vh48h0000gn/T/easy_install-2l209lya/littleutils-0.2.2/setup.cfg
Running littleutils-0.2.2/setup.py -q bdist_egg --dist-dir /var/folders/0w/lmm8ryyx5wq8qdwfny4vh48h0000gn/T/easy_install-2l209lya/littleutils-0.2.2/egg-dist-tmp-xgsigjtb
/venv/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
creating /venv/lib/python3.9/site-packages/littleutils-0.2.2-py3.9.egg
Extracting littleutils-0.2.2-py3.9.egg to /venv/lib/python3.9/site-packages
byte-compiling /venv/lib/python3.9/site-packages/littleutils-0.2.2-py3.9.egg/littleutils/__init__.py to __init__.cpython-39.pyc
Adding littleutils 0.2.2 to easy-install.pth file

Installed /venv/lib/python3.9/site-packages/littleutils-0.2.2-py3.9.egg
Searching for urllib3==2.0.7
Best match: urllib3 2.0.7
Adding urllib3 2.0.7 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for tqdm==4.66.1
Best match: tqdm 4.66.1
Adding tqdm 4.66.1 to easy-install.pth file
Installing tqdm script to /venv/bin

Using /venv/lib/python3.9/site-packages
Searching for torch==2.1.0
Best match: torch 2.1.0
Adding torch 2.1.0 to easy-install.pth file
Installing convert-caffe2-to-onnx script to /venv/bin
Installing convert-onnx-to-caffe2 script to /venv/bin
Installing torchrun script to /venv/bin

Using /venv/lib/python3.9/site-packages
Searching for scikit-learn==1.3.1
Best match: scikit-learn 1.3.1
Adding scikit-learn 1.3.1 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for numpy==1.26.1
Best match: numpy 1.26.1
Adding numpy 1.26.1 to easy-install.pth file
Installing f2py script to /venv/bin

Using /venv/lib/python3.9/site-packages
Searching for sympy==1.12
Best match: sympy 1.12
Adding sympy 1.12 to easy-install.pth file
Installing isympy script to /venv/bin

Using /venv/lib/python3.9/site-packages
Searching for networkx==3.2
Best match: networkx 3.2
Adding networkx 3.2 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for Jinja2==3.1.2
Best match: Jinja2 3.1.2
Adding Jinja2 3.1.2 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for typing-extensions==4.8.0
Best match: typing-extensions 4.8.0
Adding typing-extensions 4.8.0 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for filelock==3.12.4
Best match: filelock 3.12.4
Adding filelock 3.12.4 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for fsspec==2023.9.2
Best match: fsspec 2023.9.2
Adding fsspec 2023.9.2 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for joblib==1.3.2
Best match: joblib 1.3.2
Adding joblib 1.3.2 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for scipy==1.11.3
Best match: scipy 1.11.3
Adding scipy 1.11.3 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for threadpoolctl==3.2.0
Best match: threadpoolctl 3.2.0
Adding threadpoolctl 3.2.0 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for setuptools==60.2.0
Best match: setuptools 60.2.0
Adding setuptools 60.2.0 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for requests==2.31.0
Best match: requests 2.31.0
Adding requests 2.31.0 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for mpmath==1.3.0
Best match: mpmath 1.3.0
Adding mpmath 1.3.0 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for MarkupSafe==2.1.3
Best match: MarkupSafe 2.1.3
Adding MarkupSafe 2.1.3 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for idna==3.4
Best match: idna 3.4
Adding idna 3.4 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for certifi==2023.7.22
Best match: certifi 2023.7.22
Adding certifi 2023.7.22 to easy-install.pth file

Using /venv/lib/python3.9/site-packages
Searching for charset-normalizer==3.3.0
Best match: charset-normalizer 3.3.0
Adding charset-normalizer 3.3.0 to easy-install.pth file
Installing normalizer script to /venv/bin

Using /venv/lib/python3.9/site-packages
Finished processing dependencies for torch-geometric-autoscale==0.0.0

```

**Comment by lamthuy** [comment]
Hi, I installed pyg autoscale on linux, the installation was successful, however when I tried to run examples and benchmarks it always complain:
```
AttributeError: '_OpNamespace' 'torch_geometric_autoscale' object has no attribute 'synchronize'
```
Do you know what happens?

**Comment by manikandanbalasubramani03** [comment]
Hi @marmg.
I am also getting the same error.

Have you resolved it ? If yes could you please guide me to overcome the issue?
