### ISSUE TITLE
Issue with SubgraphLoader() and/or Torch

### ISSUE THREAD

**Issue by ersanchezo** [rusty1s/pyg_autoscale#30]
Hi, I obtained this error by just running the first example train_gcn.py

 Traceback (most recent call last):
  File "/home/ersa/spage2vec/pyg_autoscale/examples/train_gcn.py", line 85, in <module>
    train(model, loader, optimizer)
  File "/home/ersa/spage2vec/pyg_autoscale/examples/train_gcn.py", line 57, in train
    for batch, *args in loader:
  File "/home/ersa/miniconda3/envs/spage2vec/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/ersa/miniconda3/envs/spage2vec/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ersa/miniconda3/envs/spage2vec/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/ersa/miniconda3/envs/spage2vec/lib/python3.10/site-packages/torch_geometric_autoscale/loader.py", line 74, in compute_subgraph
    rowptr, col, value, n_id = relabel_fn(rowptr, col, value, n_id,
  File "/home/ersa/miniconda3/envs/spage2vec/lib/python3.10/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: isBool() INTERNAL ASSERT FAILED at "/home/ersa/miniconda3/envs/spage2vec/lib/python3.10/site-packages/torch/include/ATen/core/ivalue.h":666, please report a bug to PyTorch. 

My conda environment:
python version==3.10.13.final.0

torch                     1.13.1+cu117             pypi_0    pypi
torch-cluster             1.6.3+pt20cu117          pypi_0    pypi
torch-geometric           2.4.0                    pypi_0    pypi
torch-geometric-autoscale 0.0.0                    pypi_0    pypi
torch-scatter             2.1.2+pt20cu117          pypi_0    pypi
torch-sparse              0.6.18+pt20cu117          pypi_0    pypi

**Comment by rusty1s** [comment]
Thanks for reporting. What does
```python
import torch
import torch_geometric_autoscale
relabel_fn = torch.ops.torch_geometric_autoscale.relabel_one_hop

rowptr = torch.tensor([0, 2, 3])
col = torch.tensor([0, 1, 0])
value = torch.tensor([0, 1, 2])
n_id = torch.tensor([0, 1])

relabel_fn(rowptr, col, value, n_id, True)
relabel_fn(rowptr, col, value, n_id, False)
```
return for you?

**Comment by ersanchezo** [comment]
It returned this:
File "/home/ersa/spage2vec/trial_run/troubleshoot.py", line 10, in  "module"
    relabel_fn(rowptr, col, value, n_id, True)
  File "/home/ersa/miniconda3/envs/spage2vec/lib/python3.10/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: isBool() INTERNAL ASSERT FAILED at "/home/ersa/miniconda3/envs/spage2vec/lib/python3.10/site-packages/torch/include/ATen/core/ivalue.h":666, please report a bug to PyTorch.

**Comment by rusty1s** [comment]
Can you show me the installation log when running `python setup.py install`? Looks like something went wrong during installation.

**Comment by ersanchezo** [comment]
I accidentally deleted my conda environment, but was able to install it correctly with stable CUDA/Torch combination. Thanks for the help!

**Comment by ersanchezo** [comment]
I had installed an unstable version combination of CUDA and Torch and was fix restarting my conda environment. Thanks for the help!
